### ISSUE TITLE
SWIFT_VERSION '3.0' is unsupported

### ISSUE THREAD

**Issue by Coliinnn** [onevcat/RandomColorSwift#11]
SWIFT_VERSION '3.0' is unsupported, supported versions are: 4.0, 4.2, 5.0.

Also unable to convert to Swift 5.0, because Xcode 11 no longer supports this conversion. Does this mean this library is officially deprecated? I see previous issues and fixes, but I'm still getting this error. Installing manually didn't work, then installing with CocoaPods also did not work.

**Comment by onevcat** [comment]
Version 2.0.0 was released with all modern things (Swift 5, SPM, etc) set up!
