### ISSUE TITLE
avoid black and white 

### ISSUE THREAD

**Issue by L1cardo** [onevcat/RandomColorSwift#12]
Is there a way to get a random color except black, white and gray?

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by onevcat** [comment]
Maybe try a different `luminosity` instead of all random..Such as:

```
randomColor(hue: .random, luminosity: .light)
```

should give you a nice result.

Also, remember to run and play with the demo app in the repo to get closer to what you want.
