### ISSUE TITLE
should be changed   "import RandomColorSwift" in beginning document

### ISSUE THREAD

**Issue by wongben** [onevcat/RandomColorSwift#2]
in your Document:

exemple:

import RandomColor

should be changed "import RandomColorSwift"

**Comment by onevcat** [comment]
Fixed :). Thanks for pointing it out.

**Comment by lordlycastle** [comment]
Umm... when I build the project `RandomColor` framework is created not `RandomColorSwift`. And I the `randomColor()` is undefined when I import it. Any ideas why this is?
