### ISSUE TITLE
Swift 3

### ISSUE THREAD

**Issue by nsleche** [onevcat/RandomColorSwift#4]
it'd be cool to have a swift 3 version, if you have any interest to create a branch i would like to help with that.

**Comment by onevcat** [comment]
Sure! I created one. Thanks for considering to contribute!

**Comment by alejandrorbradford** [comment]
Working on Swift 3 by now?

**Comment by onevcat** [comment]
@alejandrorbradford  Now supported in master, and a new version (1.0.0) is released for it.
